=== jcarmena/blask/bw_old/target/src/Blask/Response/MimeTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://www.tibco.com/schemas/bw/Blask/MimeTypes.xsd"
	 targetNamespace="http://www.tibco.com/schemas/bw/Blask/MimeTypes.xsd"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:element name="mimeTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mimeType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="mimeType">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="extension" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jcarmena/blask/bw_old/target/src/Blask/Response/mimeTypesXml.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<mimeTypes xmlns = "http://www.tibco.com/schemas/bw/Blask/MimeTypes.xsd" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://www.tibco.com/schemas/bw/Blask/MimeTypes.xsd MimeTypes.xsd">
	<mimeType extension = "3dm">x-world/x-3dmf</mimeType>
	<mimeType extension = "3dmf">x-world/x-3dmf</mimeType>
	<mimeType extension = "a">application/octet-stream</mimeType>
	<mimeType extension = "aab">application/x-authorware-bin</mimeType>
	<mimeType extension = "aam">application/x-authorware-map</mimeType>
	<mimeType extension = "aas">application/x-authorware-seg</mimeType>
	<mimeType extension = "abc">text/vnd.abc</mimeType>
	<mimeType extension = "acgi">text/html</mimeType>
	<mimeType extension = "afl">video/animaflex</mimeType>
	<mimeType extension = "ai">application/postscript</mimeType>
	<mimeType extension = "aif">audio/aiff</mimeType>
	<mimeType extension = "aif">audio/x-aiff</mimeType>
	<mimeType extension = "aifc">audio/aiff</mimeType>
	<mimeType extension = "aifc">audio/x-aiff</mimeType>
	<mimeType extension = "aiff">audio/aiff</mimeType>
	<mimeType extension = "aiff">audio/x-aiff</mimeType>
	<mimeType extension = "aim">application/x-aim</mimeType>
	<mimeType extension = "aip">text/x-audiosoft-intra</mimeType>
	<mimeType extension = "ani">application/x-navi-animation</mimeType>
	<mimeType extension = "aos">application/x-nokia-9000-communicator-add-on-software</mimeType>
	<mimeType extension = "aps">application/mime</mimeType>
	<mimeType extension = "arc">application/octet-stream</mimeType>
	<mimeType extension = "arj">application/arj</mimeType>
	<mimeType extension = "arj">application/octet-stream</mimeType>
	<mimeType extension = "art">image/x-jg</mimeType>
	<mimeType extension = "asf">video/x-ms-asf</mimeType>
	<mimeType extension = "asm">text/x-asm</mimeType>
	<mimeType extension = "asp">text/asp</mimeType>
	<mimeType extension = "asx">application/x-mplayer2</mimeType>
	<mimeType extension = "asx">video/x-ms-asf</mimeType>
	<mimeType extension = "asx">video/x-ms-asf-plugin</mimeType>
	<mimeType extension = "au">audio/basic</mimeType>
	<mimeType extension = "au">audio/x-au</mimeType>
	<mimeType extension = "avi">application/x-troff-msvideo</mimeType>
	<mimeType extension = "avi">video/avi</mimeType>
	<mimeType extension = "avi">video/msvideo</mimeType>
	<mimeType extension = "avi">video/x-msvideo</mimeType>
	<mimeType extension = "avs">video/avs-video</mimeType>
	<mimeType extension = "bcpio">application/x-bcpio</mimeType>
	<mimeType extension = "bin">application/mac-binary</mimeType>
	<mimeType extension = "bin">application/macbinary</mimeType>
	<mimeType extension = "bin">application/octet-stream</mimeType>
	<mimeType extension = "bin">application/x-binary</mimeType>
	<mimeType extension = "bin">application/x-macbinary</mimeType>
	<mimeType extension = "bm">image/bmp</mimeType>
	<mimeType extension = "bmp">image/bmp</mimeType>
	<mimeType extension = "bmp">image/x-windows-bmp</mimeType>
	<mimeType extension = "boo">application/book</mimeType>
	<mimeType extension = "book">application/book</mimeType>
	<mimeType extension = "boz">application/x-bzip2</mimeType>
	<mimeType extension = "bsh">application/x-bsh</mimeType>
	<mimeType extension = "bz">application/x-bzip</mimeType>
	<mimeType extension = "bz2">application/x-bzip2</mimeType>
	<mimeType extension = "c">text/plain</mimeType>
	<mimeType extension = "c">text/x-c</mimeType>
	<mimeType extension = "c++">text/plain</mimeType>
	<mimeType extension = "cat">application/vnd.ms-pki.seccat</mimeType>
	<mimeType extension = "cc">text/plain</mimeType>
	<mimeType extension = "cc">text/x-c</mimeType>
	<mimeType extension = "ccad">application/clariscad</mimeType>
	<mimeType extension = "cco">application/x-cocoa</mimeType>
	<mimeType extension = "cdf">application/cdf</mimeType>
	<mimeType extension = "cdf">application/x-cdf</mimeType>
	<mimeType extension = "cdf">application/x-netcdf</mimeType>
	<mimeType extension = "cer">application/pkix-cert</mimeType>
	<mimeType extension = "cer">application/x-x509-ca-cert</mimeType>
	<mimeType extension = "cha">application/x-chat</mimeType>
	<mimeType extension = "chat">application/x-chat</mimeType>
	<mimeType extension = "class">application/java</mimeType>
	<mimeType extension = "class">application/java-byte-code</mimeType>
	<mimeType extension = "class">application/x-java-class</mimeType>
	<mimeType extension = "com">application/octet-stream</mimeType>
	<mimeType extension = "com">text/plain</mimeType>
	<mimeType extension = "conf">text/plain</mimeType>
	<mimeType extension = "cpio">application/x-cpio</mimeType>
	<mimeType extension = "cpp">text/x-c</mimeType>
	<mimeType extension = "cpt">application/mac-compactpro</mimeType>
	<mimeType extension = "cpt">application/x-compactpro</mimeType>
	<mimeType extension = "cpt">application/x-cpt</mimeType>
	<mimeType extension = "crl">application/pkcs-crl</mimeType>
	<mimeType extension = "crl">application/pkix-crl</mimeType>
	<mimeType extension = "crt">application/pkix-cert</mimeType>
	<mimeType extension = "crt">application/x-x509-ca-cert</mimeType>
	<mimeType extension = "crt">application/x-x509-user-cert</mimeType>
	<mimeType extension = "csh">application/x-csh</mimeType>
	<mimeType extension = "csh">text/x-script.csh</mimeType>
	<mimeType extension = "css">application/x-pointplus</mimeType>
	<mimeType extension = "css">text/css</mimeType>
	<mimeType extension = "cxx">text/plain</mimeType>
	<mimeType extension = "dcr">application/x-director</mimeType>
	<mimeType extension = "deepv">application/x-deepv</mimeType>
	<mimeType extension = "def">text/plain</mimeType>
	<mimeType extension = "der">application/x-x509-ca-cert</mimeType>
	<mimeType extension = "dif">video/x-dv</mimeType>
	<mimeType extension = "dir">application/x-director</mimeType>
	<mimeType extension = "dl">video/dl</mimeType>
	<mimeType extension = "dl">video/x-dl</mimeType>
	<mimeType extension = "doc">application/msword</mimeType>
	<mimeType extension = "dot">application/msword</mimeType>
	<mimeType extension = "dp">application/commonground</mimeType>
	<mimeType extension = "drw">application/drafting</mimeType>
	<mimeType extension = "dump">application/octet-stream</mimeType>
	<mimeType extension = "dv">video/x-dv</mimeType>
	<mimeType extension = "dvi">application/x-dvi</mimeType>
	<mimeType extension = "dwf">drawing/x-dwf (old)</mimeType>
	<mimeType extension = "dwf">model/vnd.dwf</mimeType>
	<mimeType extension = "dwg">application/acad</mimeType>
	<mimeType extension = "dwg">image/vnd.dwg</mimeType>
	<mimeType extension = "dwg">image/x-dwg</mimeType>
	<mimeType extension = "dxf">application/dxf</mimeType>
	<mimeType extension = "dxf">image/vnd.dwg</mimeType>
	<mimeType extension = "dxf">image/x-dwg</mimeType>
	<mimeType extension = "dxr">application/x-director</mimeType>
	<mimeType extension = "el">text/x-script.elisp</mimeType>
	<mimeType extension = "elc">application/x-bytecode.elisp (compiled elisp)</mimeType>
	<mimeType extension = "elc">application/x-elc</mimeType>
	<mimeType extension = "env">application/x-envoy</mimeType>
	<mimeType extension = "eps">application/postscript</mimeType>
	<mimeType extension = "es">application/x-esrehber</mimeType>
	<mimeType extension = "etx">text/x-setext</mimeType>
	<mimeType extension = "evy">application/envoy</mimeType>
	<mimeType extension = "evy">application/x-envoy</mimeType>
	<mimeType extension = "exe">application/octet-stream</mimeType>
	<mimeType extension = "f">text/plain</mimeType>
	<mimeType extension = "f">text/x-fortran</mimeType>
	<mimeType extension = "f77">text/x-fortran</mimeType>
	<mimeType extension = "f90">text/plain</mimeType>
	<mimeType extension = "f90">text/x-fortran</mimeType>
	<mimeType extension = "fdf">application/vnd.fdf</mimeType>
	<mimeType extension = "fif">application/fractals</mimeType>
	<mimeType extension = "fif">image/fif</mimeType>
	<mimeType extension = "fli">video/fli</mimeType>
	<mimeType extension = "fli">video/x-fli</mimeType>
	<mimeType extension = "flo">image/florian</mimeType>
	<mimeType extension = "flx">text/vnd.fmi.flexstor</mimeType>
	<mimeType extension = "fmf">video/x-atomic3d-feature</mimeType>
	<mimeType extension = "for">text/plain</mimeType>
	<mimeType extension = "for">text/x-fortran</mimeType>
	<mimeType extension = "fpx">image/vnd.fpx</mimeType>
	<mimeType extension = "fpx">image/vnd.net-fpx</mimeType>
	<mimeType extension = "frl">application/freeloader</mimeType>
	<mimeType extension = "funk">audio/make</mimeType>
	<mimeType extension = "g">text/plain</mimeType>
	<mimeType extension = "g3">image/g3fax</mimeType>
	<mimeType extension = "gif">image/gif</mimeType>
	<mimeType extension = "gl">video/gl</mimeType>
	<mimeType extension = "gl">video/x-gl</mimeType>
	<mimeType extension = "gsd">audio/x-gsm</mimeType>
	<mimeType extension = "gsm">audio/x-gsm</mimeType>
	<mimeType extension = "gsp">application/x-gsp</mimeType>
	<mimeType extension = "gss">application/x-gss</mimeType>
	<mimeType extension = "gtar">application/x-gtar</mimeType>
	<mimeType extension = "gz">application/x-compressed</mimeType>
	<mimeType extension = "gz">application/x-gzip</mimeType>
	<mimeType extension = "gzip">application/x-gzip</mimeType>
	<mimeType extension = "gzip">multipart/x-gzip</mimeType>
	<mimeType extension = "h">text/plain</mimeType>
	<mimeType extension = "h">text/x-h</mimeType>
	<mimeType extension = "hdf">application/x-hdf</mimeType>
	<mimeType extension = "help">application/x-helpfile</mimeType>
	<mimeType extension = "hgl">application/vnd.hp-hpgl</mimeType>
	<mimeType extension = "hh">text/plain</mimeType>
	<mimeType extension = "hh">text/x-h</mimeType>
	<mimeType extension = "hlb">text/x-script</mimeType>
	<mimeType extension = "hlp">application/hlp</mimeType>
	<mimeType extension = "hlp">application/x-helpfile</mimeType>
	<mimeType extension = "hlp">application/x-winhelp</mimeType>
	<mimeType extension = "hpg">application/vnd.hp-hpgl</mimeType>
